//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pollsNew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class objectsRElation
    {
        public int pairId { get; set; }
        public int userId { get; set; }
        public int tableId { get; set; }
        public Nullable<System.DateTime> pairDate { get; set; }
    
        public virtual table table { get; set; }
    }
}
