//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pollsNew.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pollsEntities : DbContext
    {
        public pollsEntities()
            : base("name=pollsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table> tables { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<objectsRElation> objectsRElations { get; set; }
        public virtual DbSet<tableObject> tableObjects { get; set; }
        public virtual DbSet<tableObjectPair> tableObjectPairs { get; set; }
        public virtual DbSet<attribute> attributes { get; set; }
        public virtual DbSet<poll> polls { get; set; }
    }
}
