//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pollsNew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableObjectPair
    {
        public tableObjectPair()
        {
            this.polls = new HashSet<poll>();
        }
    
        public int pairId { get; set; }
        public int tableId { get; set; }
        public int object1Id { get; set; }
        public int object2Id { get; set; }
        public int userId { get; set; }
        public Nullable<int> IsVoted { get; set; }
    
        public virtual table table { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<poll> polls { get; set; }
    }
}
