//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pollsNew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public table()
        {
            this.objectsRElations = new HashSet<objectsRElation>();
            this.tableObjects = new HashSet<tableObject>();
            this.tableObjectPairs = new HashSet<tableObjectPair>();
            this.attributes = new HashSet<attribute>();
            this.polls = new HashSet<poll>();
        }
    
        public int tableId { get; set; }
        public string tablename { get; set; }
    
        public virtual ICollection<objectsRElation> objectsRElations { get; set; }
        public virtual ICollection<tableObject> tableObjects { get; set; }
        public virtual ICollection<tableObjectPair> tableObjectPairs { get; set; }
        public virtual ICollection<attribute> attributes { get; set; }
        public virtual ICollection<poll> polls { get; set; }
    }
}
